version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes:
      - github.com/shunto-ishiguro/trip-plan-app
