version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/shunto/trip-plan-app
